### ISSUE TITLE
Allow user to optin Non amp document to be cached by AMP service worker

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amp-sw#17]
A lot of web apps are built in paired mode where some pages are valid amp while others are not.
This library has a very clear intent of not acting on the Non AMP pages.

But if a dev thinks that our approach is good enough for the NON-amp pages as well, they should have a way to opt-in for those documents in `document-caching` module.

This will be a clear opt-in from the dev's side and not us doing anything un intuitive.

**Comment by prateekbh** [comment]
// @sebastianbenz

**Comment by marcus-hiles** [comment]
👍 awesome, thanks

**Comment by prateekbh** [comment]
// @kristoferbaxter you have any views about this?

**Comment by kristoferbaxter** [comment]
Makes sense to me.
