### ISSUE TITLE
Please make the usage end-to-end

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp-sw#19]
Sine we are now widely releasing this, please polish the README and especially make the usage complete (including how to install the SW in AMP).

CC @nainar

**Comment by nainar** [comment]
@prateekbh is OOO till Monday. 

Prateek once you are back could you make this a P0?

The talk announcing this is Wednesday according to SF timezones.

**Comment by prateekbh** [comment]
Sure, I'll take care of this first thing on Monday

**Comment by prateekbh** [comment]
Fixed in #20
